server:
  address:     ":8000"
  openapiPath: "/api.json"
  swaggerPath: "/swagger"

logger:
  level : "all"
  stdout: true


database:
  default:
    type: "mysql"
    link: "root:lilishop@tcp(127.0.0.1:3306)/realworld"
    # 输出指定sql
    debug: true
    dryRun: true


gfcli:
  gen:
    dao:
    - link:     "mysql:root:lilishop@tcp(127.0.0.1:3306)/realworld"
#       tables:   "order,products"
      jsonCase: "CamelLower"
