// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/2720851545/realworld-golang-gf/internal/service/internal/dao/internal"
)

// internalFavoriteDao is internal type for wrapping internal DAO implements.
type internalFavoriteDao = *internal.FavoriteDao

// favoriteDao is the data access object for table favorite.
// You can define custom methods on it to extend its functionality as you wish.
type favoriteDao struct {
	internalFavoriteDao
}

var (
	// Favorite is globally public accessible object for table favorite operations.
	Favorite = favoriteDao{
		internal.NewFavoriteDao(),
	}
)

// Fill with you ideas below.
