// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// Follow is the golang structure of table follow for DAO operations like Where/Data.
type Follow struct {
	g.Meta       `orm:"table:follow, do:true"`
	Id           interface{} //
	CreatedAt    *gtime.Time //
	UpdatedAt    *gtime.Time //
	DeletedAt    *gtime.Time //
	FollowingId  interface{} //
	FollowedById interface{} //
}
