// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// ArticleTags is the golang structure for table article_tags.
type ArticleTags struct {
	ArticleModelId int `json:"articleModelId" ` //
	TagModelId     int `json:"tagModelId"     ` //
}
