// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// Article is the golang structure for table article.
type Article struct {
	Id          int         `json:"id"          ` //
	CreatedAt   *gtime.Time `json:"createdAt"   ` //
	UpdatedAt   *gtime.Time `json:"updatedAt"   ` //
	DeletedAt   *gtime.Time `json:"deletedAt"   ` //
	Slug        string      `json:"slug"        ` //
	Title       string      `json:"title"       ` //
	Description string      `json:"description" ` //
	Body        string      `json:"body"        ` //
	AuthorId    int         `json:"authorId"    ` //
}
