// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// ArticleUser is the golang structure for table article_user.
type ArticleUser struct {
	Id          int         `json:"id"          ` //
	CreatedAt   *gtime.Time `json:"createdAt"   ` //
	UpdatedAt   *gtime.Time `json:"updatedAt"   ` //
	DeletedAt   *gtime.Time `json:"deletedAt"   ` //
	UserModelId int         `json:"userModelId" ` //
}
