// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// Favorite is the golang structure for table favorite.
type Favorite struct {
	Id           int         `json:"id"           ` //
	CreatedAt    *gtime.Time `json:"createdAt"    ` //
	UpdatedAt    *gtime.Time `json:"updatedAt"    ` //
	DeletedAt    *gtime.Time `json:"deletedAt"    ` //
	FavoriteId   int         `json:"favoriteId"   ` //
	FavoriteById int         `json:"favoriteById" ` //
}
