// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// Follow is the golang structure for table follow.
type Follow struct {
	Id           int         `json:"id"           ` //
	CreatedAt    *gtime.Time `json:"createdAt"    ` //
	UpdatedAt    *gtime.Time `json:"updatedAt"    ` //
	DeletedAt    *gtime.Time `json:"deletedAt"    ` //
	FollowingId  int         `json:"followingId"  ` //
	FollowedById int         `json:"followedById" ` //
}
