// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// User is the golang structure for table user.
type User struct {
	Id       int    `json:"id"       ` //
	Username string `json:"username" ` // 用户名
	Email    string `json:"email"    ` // 邮箱
	Bio      []byte `json:"bio"      ` // 介绍
	Image    string `json:"image"    ` // 头像
	Password string `json:"password" ` // 密码
}
